import logging
import os
import requests
import urllib.parse
from flask import Flask
from threading import Thread
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# --- Flask Server for Render (Keep Alive) ---
app = Flask('')

@app.route('/')
def home():
    return "AI Image Bot is running!"

def run():
    port = int(os.environ.get("PORT", 8080))
    app.run(host='0.0.0.0', port=port)

def keep_alive():
    t = Thread(target=run)
    t.start()

# --- Bot Settings ---
# @BotFather থেকে আপনার নতুন বটের টোকেনটি এখানে বসান
TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN'

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👋 Welcome to AI Image Generator Bot!\n\n"
        "Just send me a description of what you want to see, and I will create an image for you.\n\n"
        "Example: `A futuristic city with flying cars`"
    )

async def generate_image(update: Update, context: ContextTypes.DEFAULT_TYPE):
    prompt = update.message.text
    
    if not prompt:
        return

    # ইউজারকে জানানো হচ্ছে যে কাজ চলছে
    status_msg = await update.message.reply_text("🎨 Generating your image... please wait.")

    try:
        # প্রম্পটটিকে ইউআরএল ফ্রেন্ডলি করা হচ্ছে
        encoded_prompt = urllib.parse.quote(prompt)
        
        # Pollinations AI এর ফ্রি ইমেজ জেনারেশন লিঙ্ক
        image_url = f"https://pollinations.ai/p/{encoded_prompt}?width=1024&height=1024&seed={random.randint(1, 100000)}&model=flux"

        # টেলিগ্রামে ছবি পাঠানো
        await update.message.reply_photo(
            photo=image_url,
            caption=f"✨ **Result for:** {prompt}\n\nGenerated by @YourBotName",
            parse_mode='Markdown'
        )
        
        # স্ট্যাটাস মেসেজটি ডিলিট করে দেওয়া
        await status_msg.delete()

    except Exception as e:
        logging.error(e)
        await status_msg.edit_text("❌ Sorry, something went wrong while generating the image.")

import random # র্যান্ডম সিডের জন্য প্রয়োজন

def main():
    keep_alive() # রেন্ডারের জন্য জরুরি
    app_bot = Application.builder().token(TOKEN).build()
    
    app_bot.add_handler(CommandHandler("start", start))
    app_bot.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, generate_image))
    
    print("AI Image Bot started!")
    app_bot.run_polling()

if __name__ == '__main__':
    main()
